version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbGroup10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: dbGroup10
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "3001:3001"
    networks:
      - backend
    command: sh -c "node ./scripts/seeds.js && npm start"

volumes:
  pgdata:

networks:
  backend:
