name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # BACKEND (Node + Docker)

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Créer fichier .env temporaire
        working-directory: ./backend
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "JWT_SECRET=LaVue" >> .env
          echo "ACCESS_TOKEN_EXPIRES=2d" >> .env
          echo "REFRESH_TOKEN_EXPIRES=7d" >> .env
          echo "NODE_ENV=production" >> .env
          echo "PORT=3001" >> .env

      - name: Test backend
        working-directory: ./backend
        run: npm test

      - name: Build Docker image (backend)
        working-directory: ./backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-tp-gl:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-tp-gl:latest

      # FRONTEND (React JS)

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest


           

  deploy:
    name: Deploy backend to Render
    needs: build-test-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  Deploy-Preview:
    name: Deploy frontend to vercel
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull Vercel Environment Information
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}